CREATE DATABASE QuanLyKhoa;
USE QuanLyKhoa;

-- TABLE KHOA
CREATE TABLE KHOA(
    MAKHOA VARCHAR(10) PRIMARY KEY,
    TENKHOA VARCHAR(50),
    NGTLAP DATE,
    TRGKHOA VARCHAR(10)
);

-- TABLE GIAOVIEN
CREATE TABLE GIAOVIEN(
    MAGV VARCHAR(10) PRIMARY KEY,
    HOTEN VARCHAR(50),
    HOCVI VARCHAR(30),
    HOCHAM VARCHAR(30),
    GIOITINH VARCHAR(10),
    HESO FLOAT,
    MUCLUONG DOUBLE,
    MAKHOA VARCHAR(10),
    FOREIGN KEY(MAKHOA)
    REFERENCES KHOA(MAKHOA)
);

-- DATA KHOA
INSERT INTO KHOA VALUES
('CNTT','Cong Nghe Thong Tin','2020-01-01',NULL),
('KT','Ke Toan','2019-05-10',NULL);

-- DATA GIAOVIEN
INSERT INTO GIAOVIEN VALUES
('GV01','Nguyen Van A','Tien Si','Pho Giao Su','Nam',3.2,15000000,'CNTT'),
('GV02','Tran Thi B','Thac Si','Giang Vien','Nu',2.8,12000000,'CNTT'),
('GV03','Le Van C','Tien Si','Giao Su','Nam',4.0,20000000,'KT');